package cmd

import (
	"log"
	"os"
	"path/filepath"

	"github.com/mengelbart/cgo-streamer/benchmark"
	"github.com/spf13/cobra"
)

func init() {
	rootCmd.AddCommand(uploadCmd)
}

var uploadCmd = &cobra.Command{
	Use: "upload",
	Long: `upload a data directory generated by the bench command to google cloud.
Requires a valid project to be setup to use cloud storage and firestore and
GOOGLE_APPLICATION_CREDENTIALS to be set to a valid value (see 
https://developers.google.com/accounts/docs/application-default-credentials
for more information).`,
	RunE: func(cmd *cobra.Command, args []string) error {
		return upload()
	},
}

func upload() error {
	uploader, err := benchmark.NewUploader(Commit)
	if err != nil {
		return err
	}
	err = filepath.Walk("./data", func(path string, info os.FileInfo, err error) error {
		if info.Name() == "config.json" {
			err := uploader.Upload(filepath.Dir(path))
			if err != nil {
				log.Printf("failed to upload experiment: %v\n", path)
			}
		}
		return nil
	})
	return nil
}
